# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xm_xmjbxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmbm', models.CharField(max_length=50)),
                ('xmnc', models.CharField(max_length=20)),
            ],
        ),
    ]
