# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzcgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('userlevel', models.IntegerField()),
            ],
        ),
    ]
